# Generated by Django 4.1.7 on 2023-02-19 11:39

from django.db import migrations, models
import django.db.models.deletion
import shelterApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopting',
            fields=[
                ('adoptingId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, validators=[shelterApp.models.NamesValidation])),
                ('lastName', models.CharField(max_length=45, validators=[shelterApp.models.NamesValidation])),
                ('birthDate', models.DateField(validators=[shelterApp.models.BirthDateValidation])),
                ('city', models.CharField(max_length=45, validators=[shelterApp.models.NamesValidation])),
                ('postcode', models.CharField(max_length=6, validators=[shelterApp.models.PostcodeValidation])),
                ('address', models.CharField(max_length=45)),
                ('phoneNumber', models.IntegerField(validators=[shelterApp.models.PhoneNumberValidation])),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('diseasesId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('petId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, validators=[shelterApp.models.NamesValidation])),
                ('number', models.CharField(max_length=9)),
                ('findDate', models.DateField(validators=[shelterApp.models.EarlierDateValidation])),
                ('findPlace', models.CharField(max_length=45)),
                ('type', models.CharField(choices=[('dog', 'Pies'), ('cat', 'Kot')], default='dog', max_length=3)),
                ('age', models.IntegerField(validators=[shelterApp.models.AgeValidation])),
                ('race', models.CharField(max_length=45, validators=[shelterApp.models.NamesValidation])),
                ('weight', models.IntegerField(validators=[shelterApp.models.WeightValidation])),
                ('sex', models.CharField(choices=[('M', 'Samiec'), ('F', 'Samica')], default='M', max_length=1)),
                ('state', models.CharField(choices=[('TA', 'Do adopcji'), ('IL', 'Chory'), ('IS', 'Izolowany'), ('AD', 'Adoptowany')], default='TA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ResourcesType',
            fields=[
                ('ResourcesTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('volunteerId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, validators=[shelterApp.models.NamesValidation])),
                ('lastName', models.CharField(max_length=45, validators=[shelterApp.models.NamesValidation])),
                ('birthDate', models.DateField(validators=[shelterApp.models.BirthDateValidation])),
                ('city', models.CharField(max_length=45, validators=[shelterApp.models.NamesValidation])),
                ('postcode', models.CharField(max_length=6, validators=[shelterApp.models.PostcodeValidation])),
                ('address', models.CharField(max_length=45)),
                ('phoneNumber', models.IntegerField(validators=[shelterApp.models.PhoneNumberValidation])),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('workerId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, validators=[shelterApp.models.NamesValidation])),
                ('lastName', models.CharField(max_length=45, validators=[shelterApp.models.NamesValidation])),
                ('birthDate', models.DateField(validators=[shelterApp.models.BirthDateValidation])),
                ('city', models.CharField(max_length=45, validators=[shelterApp.models.NamesValidation])),
                ('postcode', models.CharField(max_length=6, validators=[shelterApp.models.PostcodeValidation])),
                ('address', models.CharField(max_length=45)),
                ('phoneNumber', models.IntegerField(validators=[shelterApp.models.PhoneNumberValidation])),
                ('profession', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerRequest',
            fields=[
                ('RequestId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=255)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterApp.worker')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerMeeting',
            fields=[
                ('VolunteerMeetingId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(validators=[shelterApp.models.EarlierDateValidation])),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelterApp.pets')),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelterApp.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('VacationId', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField(validators=[shelterApp.models.EarlierDateValidation])),
                ('endDate', models.DateField(validators=[shelterApp.models.DateValidation])),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterApp.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('ResourcesId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('quantity', models.IntegerField(validators=[shelterApp.models.QuantityValidation])),
                ('expiryDate', models.DateField(validators=[shelterApp.models.DateValidation])),
                ('status', models.BooleanField(default=True)),
                ('resourceType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelterApp.resourcestype')),
            ],
        ),
        migrations.CreateModel(
            name='PetDisease',
            fields=[
                ('petDiseaseId', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField(validators=[shelterApp.models.EarlierDateValidation])),
                ('endDate', models.DateField(validators=[shelterApp.models.DateValidation])),
                ('diseases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterApp.diseases')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterApp.pets')),
            ],
        ),
        migrations.CreateModel(
            name='Isolations',
            fields=[
                ('isolationId', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=45)),
                ('startDate', models.DateField(validators=[shelterApp.models.EarlierDateValidation])),
                ('endDate', models.DateField(validators=[shelterApp.models.DateValidation])),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterApp.pets')),
            ],
        ),
        migrations.CreateModel(
            name='Adoptions',
            fields=[
                ('adoptionsId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(validators=[shelterApp.models.EarlierDateValidation])),
                ('adopting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelterApp.adopting')),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelterApp.pets')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelterApp.worker')),
            ],
        ),
    ]
