# Generated by Django 4.1.7 on 2023-02-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelterApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pets',
            new_name='Pet',
        ),
        migrations.RenameField(
            model_name='diseases',
            old_name='diseasesId',
            new_name='diseaseId',
        ),
    ]
