# Generated by Django 4.1.7 on 2023-02-19 12:29

from django.db import migrations, models
import django.db.models.deletion
import shelterApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterApp', '0002_rename_pets_pet_rename_diseasesid_diseases_diseaseid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetsDiseases',
            fields=[
                ('petDiseaseId', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField(validators=[shelterApp.models.EarlierDateValidation])),
                ('endDate', models.DateField(validators=[shelterApp.models.DateValidation])),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterApp.diseases')),
            ],
        ),
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('VacationId', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField(validators=[shelterApp.models.EarlierDateValidation])),
                ('endDate', models.DateField(validators=[shelterApp.models.DateValidation])),
            ],
        ),
        migrations.RenameModel(
            old_name='Adopting',
            new_name='Adoptings',
        ),
        migrations.RenameModel(
            old_name='ResourcesType',
            new_name='ResourcesTypes',
        ),
        migrations.RenameModel(
            old_name='VolunteerMeeting',
            new_name='VolunteerMeetings',
        ),
        migrations.RenameModel(
            old_name='Volunteer',
            new_name='Volunteers',
        ),
        migrations.RenameModel(
            old_name='WorkerRequest',
            new_name='WorkerRequests',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='worker',
        ),
        migrations.RenameModel(
            old_name='Pet',
            new_name='Pets',
        ),
        migrations.RenameModel(
            old_name='Worker',
            new_name='Workers',
        ),
        migrations.DeleteModel(
            name='PetDisease',
        ),
        migrations.DeleteModel(
            name='Vacation',
        ),
        migrations.AddField(
            model_name='vacations',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterApp.workers'),
        ),
        migrations.AddField(
            model_name='petsdiseases',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterApp.pets'),
        ),
    ]
