# Generated by Django 4.1.7 on 2023-02-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelterApp', '0003_petsdiseases_vacations_rename_adopting_adoptings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adoptings',
            new_name='Adopting',
        ),
    ]
