# Generated by Django 4.1.7 on 2023-02-19 14:39

from django.db import migrations, models
import shelterApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterApp', '0004_rename_adoptings_adopting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='number',
            field=models.CharField(max_length=9, validators=[shelterApp.models.NumberValidation]),
        ),
        migrations.AlterField(
            model_name='pets',
            name='sex',
            field=models.CharField(choices=[('Samiec', 'Samiec'), ('Samica', 'Samica')], default='Samiec', max_length=6),
        ),
        migrations.AlterField(
            model_name='pets',
            name='state',
            field=models.CharField(choices=[('Do adopcji', 'Do adopcji'), ('Chory', 'Chory'), ('Izolowany', 'Izolowany'), ('Adoptowany', 'Adoptowany')], default='Do adopcji', max_length=10),
        ),
        migrations.AlterField(
            model_name='pets',
            name='type',
            field=models.CharField(choices=[('Pies', 'Pies'), ('Kot', 'Kot')], default='Pies', max_length=4),
        ),
    ]
